//! Compile-time simulator chrome translations.
//!
//! Stable language tags are persisted in settings; game-authored text remains
//! entirely outside this host localization layer.

const input = @import("input.zig");

/// Languages shipped in the binary.  Stable tags are also used by the
/// settings file, so never rename an existing enum field.
pub const Language = enum {
    pt_br,
    pt_pt,
    es,
    en,

    pub fn tag(self: Language) []const u8 {
        return @tagName(self);
    }

    pub fn fromTag(value: []const u8) ?Language {
        inline for (@typeInfo(Language).@"enum".fields) |field| {
            if (std.mem.eql(u8, value, field.name)) return @enumFromInt(field.value);
        }
        return null;
    }
};

const std = @import("std");

pub const all_languages = [_]Language{ .pt_br, .pt_pt, .es, .en };

pub fn languageName(language: Language) []const u8 {
    return switch (language) {
        .pt_br => "Português (Brasil)",
        .pt_pt => "Português (Portugal)",
        .es => "Español",
        .en => "English",
    };
}

pub const Text = struct {
    demos_title: []const u8,
    navigate_hint: []const u8,
    no_demos: []const u8,
    add_games: []const u8,
    official_demos: []const u8,
    elis_demos: []const u8,
    language: []const u8,
    controls: []const u8,
    quit: []const u8,
    detected_startup: []const u8,
    update_demos: []const u8,
    update_question: []const u8,
    existing_versions: []const u8,
    replace_only_yes: []const u8,
    yes_no_hint: []const u8,
    menu: []const u8,
    return_demos: []const u8,
    escape_back: []const u8,
    choose_language: []const u8,
    language_hint: []const u8,
    controls_title: []const u8,
    keyboard_1: []const u8,
    keyboard_2: []const u8,
    keyboard_3: []const u8,
    gamepad: []const u8,
    controls_hint: []const u8,
    controls_edit_hint: []const u8,
    waiting_key: []const u8,
    waiting_button: []const u8,
    unbound: []const u8,
    saved: []const u8,
    save_failed: []const u8,
    conflict: []const u8,
    defaults_restored: []const u8,
    status_loading: []const u8,
    status_finished: []const u8,
    status_failed: []const u8,
    searching: []const u8,
    update_failed: []const u8,
    network_failed: []const u8,
    catalog_missing: []const u8,
    codec_download_failed: []const u8,
    codec_extract_failed: []const u8,
    codec_invalid: []const u8,
    demo_prepare_failed: []const u8,
    audio_copy_failed: []const u8,
    demos_updated: []const u8,
    no_updates: []const u8,
};

pub fn get(language: Language) Text {
    return switch (language) {
        .pt_br => .{
            .demos_title = "DEMOS LUPI",
            .navigate_hint = "CIMA/BAIXO SELECIONA   ENTER CONFIRMA",
            .no_demos = "NENHUM DEMO ENCONTRADO",
            .add_games = "ADICIONE JOGOS EM demos/",
            .official_demos = "DEMOS OFICIAIS",
            .elis_demos = "DEMOS ELIS",
            .language = "IDIOMA",
            .controls = "CONTROLES",
            .quit = "SAIR DO SIMULADOR",
            .detected_startup = "DETECTADOS AO INICIAR",
            .update_demos = "U ATUALIZAR DEMOS OFICIAIS",
            .update_question = "ATUALIZAR DEMOS OFICIAIS?",
            .existing_versions = "VERSOES EXISTENTES SERAO",
            .replace_only_yes = "SUBSTITUIDAS SOMENTE COM SIM",
            .yes_no_hint = "ENTER SIM   ESC NAO",
            .menu = "MENU",
            .return_demos = "VOLTAR AOS DEMOS",
            .escape_back = "ESC VOLTA",
            .choose_language = "ESCOLHER IDIOMA",
            .language_hint = "CIMA/BAIXO   ENTER APLICA   ESC VOLTA",
            .controls_title = "REMAPEAR CONTROLES",
            .keyboard_1 = "TECLADO 1",
            .keyboard_2 = "TECLADO 2",
            .keyboard_3 = "TECLADO 3",
            .gamepad = "CONTROLE",
            .controls_hint = "ESQ/DIR ABA   ENTER ALTERA",
            .controls_edit_hint = "DEL LIMPA   R RESTAURA   ESC VOLTA",
            .waiting_key = "PRESSIONE UMA TECLA",
            .waiting_button = "PRESSIONE UM BOTAO",
            .unbound = "SEM TECLA",
            .saved = "CONFIGURACAO SALVA",
            .save_failed = "FALHA AO SALVAR",
            .conflict = "JA USADO POR",
            .defaults_restored = "PADROES RESTAURADOS",
            .status_loading = "CARREGANDO:",
            .status_finished = "CONCLUIDO:",
            .status_failed = "FALHOU:",
            .searching = "BUSCANDO DEMOS...",
            .update_failed = "FALHA AO ATUALIZAR",
            .network_failed = "FALHA AO INICIAR REDE",
            .catalog_missing = "CATALOGO NAO ENCONTRADO",
            .codec_download_failed = "FALHA AO BAIXAR O CODEC",
            .codec_extract_failed = "FALHA AO EXTRAIR O CODEC",
            .codec_invalid = "CODEC INVALIDO",
            .demo_prepare_failed = "FALHA AO PREPARAR DEMO",
            .audio_copy_failed = "FALHA AO COPIAR AUDIO",
            .demos_updated = "DEMOS ATUALIZADOS",
            .no_updates = "NENHUMA ATUALIZACAO",
        },
        .pt_pt => .{
            .demos_title = "DEMOS LUPI",
            .navigate_hint = "CIMA/BAIXO SELECIONA   ENTER CONFIRMA",
            .no_demos = "NENHUMA DEMO ENCONTRADA",
            .add_games = "ADICIONE JOGOS EM demos/",
            .official_demos = "DEMOS OFICIAIS",
            .elis_demos = "DEMOS ELIS",
            .language = "IDIOMA",
            .controls = "COMANDOS",
            .quit = "SAIR DO SIMULADOR",
            .detected_startup = "DETECTADAS AO INICIAR",
            .update_demos = "U TRANSFERIR DEMOS OFICIAIS",
            .update_question = "ATUALIZAR DEMOS OFICIAIS?",
            .existing_versions = "AS VERSOES EXISTENTES SERAO",
            .replace_only_yes = "SUBSTITUIDAS APENAS COM SIM",
            .yes_no_hint = "ENTER SIM   ESC NAO",
            .menu = "MENU",
            .return_demos = "VOLTAR AS DEMOS",
            .escape_back = "ESC VOLTA",
            .choose_language = "ESCOLHER IDIOMA",
            .language_hint = "CIMA/BAIXO   ENTER APLICA   ESC VOLTA",
            .controls_title = "REMAPEAR COMANDOS",
            .keyboard_1 = "TECLADO 1",
            .keyboard_2 = "TECLADO 2",
            .keyboard_3 = "TECLADO 3",
            .gamepad = "COMANDO",
            .controls_hint = "ESQ/DIR ABA   ENTER ALTERA",
            .controls_edit_hint = "DEL LIMPA   R REPÕE   ESC VOLTA",
            .waiting_key = "PRIMA UMA TECLA",
            .waiting_button = "PRIMA UM BOTAO",
            .unbound = "SEM TECLA",
            .saved = "CONFIGURACAO GUARDADA",
            .save_failed = "FALHA AO GUARDAR",
            .conflict = "JA USADO POR",
            .defaults_restored = "PADROES REPOSTOS",
            .status_loading = "A CARREGAR:",
            .status_finished = "CONCLUIDO:",
            .status_failed = "FALHOU:",
            .searching = "A PROCURAR DEMOS...",
            .update_failed = "FALHA AO ATUALIZAR",
            .network_failed = "FALHA AO INICIAR REDE",
            .catalog_missing = "CATALOGO NAO ENCONTRADO",
            .codec_download_failed = "FALHA AO TRANSFERIR CODEC",
            .codec_extract_failed = "FALHA AO EXTRAIR O CODEC",
            .codec_invalid = "CODEC INVALIDO",
            .demo_prepare_failed = "FALHA AO PREPARAR DEMO",
            .audio_copy_failed = "FALHA AO COPIAR AUDIO",
            .demos_updated = "DEMOS ATUALIZADAS",
            .no_updates = "SEM ATUALIZACOES",
        },
        .es => .{
            .demos_title = "DEMOS LUPI",
            .navigate_hint = "ARRIBA/ABAJO ELIGE   ENTER CONFIRMA",
            .no_demos = "NO SE ENCONTRARON DEMOS",
            .add_games = "AÑADE JUEGOS EN demos/",
            .official_demos = "DEMOS OFICIALES",
            .elis_demos = "DEMOS ELIS",
            .language = "IDIOMA",
            .controls = "CONTROLES",
            .quit = "SALIR DEL SIMULADOR",
            .detected_startup = "DETECTADOS AL INICIAR",
            .update_demos = "U ACTUALIZAR DEMOS OFICIALES",
            .update_question = "ACTUALIZAR DEMOS OFICIALES?",
            .existing_versions = "LAS VERSIONES EXISTENTES",
            .replace_only_yes = "SE SUSTITUYEN SOLO CON SI",
            .yes_no_hint = "ENTER SI   ESC NO",
            .menu = "MENU",
            .return_demos = "VOLVER A LAS DEMOS",
            .escape_back = "ESC VOLVER",
            .choose_language = "ELEGIR IDIOMA",
            .language_hint = "ARRIBA/ABAJO   ENTER APLICA   ESC VOLVER",
            .controls_title = "REMAPEAR CONTROLES",
            .keyboard_1 = "TECLADO 1",
            .keyboard_2 = "TECLADO 2",
            .keyboard_3 = "TECLADO 3",
            .gamepad = "MANDO",
            .controls_hint = "IZQ/DER PESTAÑA   ENTER CAMBIA",
            .controls_edit_hint = "SUPR BORRA   R RESTAURA   ESC VOLVER",
            .waiting_key = "PULSA UNA TECLA",
            .waiting_button = "PULSA UN BOTON",
            .unbound = "SIN ASIGNAR",
            .saved = "CONFIGURACION GUARDADA",
            .save_failed = "ERROR AL GUARDAR",
            .conflict = "YA USADO POR",
            .defaults_restored = "VALORES RESTAURADOS",
            .status_loading = "CARGANDO:",
            .status_finished = "FINALIZADO:",
            .status_failed = "ERROR:",
            .searching = "BUSCANDO DEMOS...",
            .update_failed = "ERROR AL ACTUALIZAR",
            .network_failed = "ERROR AL INICIAR LA RED",
            .catalog_missing = "CATALOGO NO ENCONTRADO",
            .codec_download_failed = "ERROR AL BAJAR EL CODEC",
            .codec_extract_failed = "ERROR AL EXTRAER EL CODEC",
            .codec_invalid = "CODEC INVALIDO",
            .demo_prepare_failed = "ERROR AL PREPARAR LA DEMO",
            .audio_copy_failed = "ERROR AL COPIAR AUDIO",
            .demos_updated = "DEMOS ACTUALIZADAS",
            .no_updates = "NO HAY ACTUALIZACIONES",
        },
        .en => .{
            .demos_title = "LUPI DEMOS",
            .navigate_hint = "UP/DOWN SELECTS   ENTER CONFIRMS",
            .no_demos = "NO DEMOS FOUND",
            .add_games = "ADD GAMES TO demos/",
            .official_demos = "OFFICIAL DEMOS",
            .elis_demos = "ELIS DEMOS",
            .language = "LANGUAGE",
            .controls = "CONTROLS",
            .quit = "QUIT SIMULATOR",
            .detected_startup = "DETECTED AT STARTUP",
            .update_demos = "U UPDATE OFFICIAL DEMOS",
            .update_question = "UPDATE OFFICIAL DEMOS?",
            .existing_versions = "EXISTING VERSIONS WILL BE",
            .replace_only_yes = "REPLACED ONLY IF YOU ACCEPT",
            .yes_no_hint = "ENTER YES   ESC NO",
            .menu = "MENU",
            .return_demos = "RETURN TO DEMOS",
            .escape_back = "ESC BACK",
            .choose_language = "CHOOSE LANGUAGE",
            .language_hint = "UP/DOWN   ENTER APPLIES   ESC BACK",
            .controls_title = "REMAP CONTROLS",
            .keyboard_1 = "KEYBOARD 1",
            .keyboard_2 = "KEYBOARD 2",
            .keyboard_3 = "KEYBOARD 3",
            .gamepad = "GAMEPAD",
            .controls_hint = "LEFT/RIGHT TAB   ENTER CHANGES",
            .controls_edit_hint = "DEL CLEARS   R RESETS   ESC BACK",
            .waiting_key = "PRESS A KEY",
            .waiting_button = "PRESS A BUTTON",
            .unbound = "UNBOUND",
            .saved = "SETTINGS SAVED",
            .save_failed = "FAILED TO SAVE",
            .conflict = "ALREADY USED BY",
            .defaults_restored = "DEFAULTS RESTORED",
            .status_loading = "LOADING:",
            .status_finished = "FINISHED:",
            .status_failed = "FAILED:",
            .searching = "SEARCHING FOR DEMOS...",
            .update_failed = "FAILED TO UPDATE",
            .network_failed = "FAILED TO START NETWORK",
            .catalog_missing = "CATALOG NOT FOUND",
            .codec_download_failed = "FAILED TO DOWNLOAD CODEC",
            .codec_extract_failed = "FAILED TO EXTRACT CODEC",
            .codec_invalid = "INVALID CODEC",
            .demo_prepare_failed = "FAILED TO PREPARE DEMO",
            .audio_copy_failed = "FAILED TO COPY AUDIO",
            .demos_updated = "DEMOS UPDATED",
            .no_updates = "NO UPDATES AVAILABLE",
        },
    };
}

pub fn actionName(language: Language, action: input.Action) []const u8 {
    return switch (language) {
        .pt_br, .pt_pt => switch (action) {
            .up => "CIMA",
            .down => "BAIXO",
            .left => "ESQUERDA",
            .right => "DIREITA",
            .primary => "ACAO Z / A",
            .secondary => "ACAO X / B",
            .face_x => "ACAO E / X",
            .face_y => "ACAO Q / Y",
            .shoulder_l => "OMBRO L",
            .shoulder_r => "OMBRO R",
            .select => "SELECT",
            .start => "START",
        },
        .es => switch (action) {
            .up => "ARRIBA",
            .down => "ABAJO",
            .left => "IZQUIERDA",
            .right => "DERECHA",
            .primary => "ACCION Z / A",
            .secondary => "ACCION X / B",
            .face_x => "ACCION E / X",
            .face_y => "ACCION Q / Y",
            .shoulder_l => "HOMBRO L",
            .shoulder_r => "HOMBRO R",
            .select => "SELECT",
            .start => "START",
        },
        .en => switch (action) {
            .up => "UP",
            .down => "DOWN",
            .left => "LEFT",
            .right => "RIGHT",
            .primary => "ACTION Z / A",
            .secondary => "ACTION X / B",
            .face_x => "ACTION E / X",
            .face_y => "ACTION Q / Y",
            .shoulder_l => "SHOULDER L",
            .shoulder_r => "SHOULDER R",
            .select => "SELECT",
            .start => "START",
        },
    };
}
